#!/usr/bin/env zsh
if [[ -z  $STOW_FOLDER ]]; then
    STOW_FOLDERS="zsh,nvim,picom,rofi,kitty,tmux,awesome"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
